# Copyright 2011 Eric Clark. All rights reserved.
# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

DEPS=../../bson/bsoncompat

TARG=github.com/eclark/exl/mongo/gridfs
GOFILES=\
	gridfs.go\

include $(GOROOT)/src/Make.pkg
