# Copyright 2011 Eric Clark. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/eclark/exl/par2
GOFILES=\
	par2.go\
	util.go\
	main.go\
	filedescriptor.go\
	ifsc.go\
	creator.go\

include $(GOROOT)/src/Make.pkg
